# Generated by Django 3.2.4 on 2021-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdatainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('Qualification', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('pannum', models.CharField(max_length=30)),
                ('request_received', models.DateTimeField()),
            ],
        ),
    ]
